version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    networks:
      - front-tier
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/app"
      - "/app/node_modules"
    ports:
      - "5001:80"
    tty: true
    stdin_open: true
    networks:
      - back-tier
  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
