version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/app"
      - "/app/node_modules"
    tty: true
    stdin_open: true
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
  redis:
    image: redis:alpine
    container_name: redis
